### ISSUE TITLE
Rendered text is too wide on Chrome

### ISSUE THREAD

**Issue by SpainTrain** [jxnblk/react-fitter-happier-text#4]
Looks to be having an issue on Chrome, at least on:
- Chrome 53.0.2785.116 (64-bit) on Ubuntu 16.04.1 LTS
- Chrome 53.0.2785.116 (64-bit) on OS X 10.11.6 

![selection_198](https://cloud.githubusercontent.com/assets/380032/18798252/95a7fe60-819f-11e6-993f-4c98131c8e73.png)

**Comment by wub** [comment]
@jxnblk Same here, Chrome 58 and 59, 64-bit, Windows.

**Comment by mrtysn** [comment]
I have the same issue, Chromium Version 61.0.3163.100 (Developer Build) (64-bit)

**Comment by santiagovazquez** [comment]
Same here, Chrome Version 68.0.3440.106 (Official Build) (64-bit) on MacOS High Sierra
