### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Nantris** [jxnblk/react-fitter-happier-text#9]
I figure this library is probably too old to still work for some reason or another, but I'd love to see how it works. The demo page won't load `bundle.js`

Firefox console message: `Loading failed for the <script> with source “http://jxnblk.com/bundle.js”.`

PS, love the Radiohead reference.

**Comment by jxnblk** [comment]
This repo should be archived, but the domain for the demo has changed to http://jxnblk.github.io/react-fitter-happier-text/ - the same principle was used in https://github.com/jxnblk/fitter-happier-text FWIW
